### PR TITLE
Laravel 8

### PR DESCRIPTION
**Pull request by C0kkie**
Hello its me again 👍 
now again with a PR for laravel 8

### CODE REVIEW

**Comment by C0kkie** [comment]
@gghughunishvili

**Comment by C0kkie** [comment]
Could you approve pls :(

**Comment by gghughunishvili** [comment]
@C0kkie Sorry but I couldn't confirm that the solution works and I can't merge something that I'm not sure about. The only thing I can do is to add a new branch with your changes so you could continue working with it in your project.

I'm very busy at this moment and I will find some time in 2 weeks to properly upgrade it with the latest version.

**Comment by gghughunishvili** [comment]
@C0kkie you could use this version: https://github.com/gghughunishvili/entrust/releases/tag/rc-4

**Comment by Levivb** [comment]
rc-4 seems to be working for us no problem. A stable tag should be okay :)

**Pull request closed without merging**
